<a href="https://colab.research.google.com/github/kempy/tf-scratch/blob/master/Stack_Overflow_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### [What's the equivalent of this Numpy code in TensorFlow?](https://stackoverflow.com/questions/55839030/whats-the-equivalent-of-this-numpy-code-in-tensorflow/55839581#55839581)

I am manipulating Numpy arrays, and the code looks like the following:

    z[np.arange(n), y]
    
Where z is a 2d array, y is a 1d array. Further, z.shape[0] == y.shape[0] == n.

How can I do equivalent things to TensorFlow tensors?

In [28]:
import numpy as np
import tensorflow as tf

n = 3
z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([0, 1, 1])

assert z.shape[0] == y.shape[0] == n

# Numpy implementation
np_out = z[np.arange(n), y]

# TF implementation
tf.reset_default_graph()

range_t = tf.range(n) # Equiv to np.arange
x_y = tf.stack([range_t, y], axis=1) # Get (x,y) as a tuple
pick_by_index_from_z = tf.gather_nd(z, x_y) # Pick the right values from z

with tf.Session() as sess:
  tf_out = sess.run(pick_by_index_from_z)

# The np and tf implementations should be the same
assert (np_out == tf_out).all()

print('z:')
print(z)
print('\nnp_out:')
print(np_out)
print('\ntf_out:')
print(tf_out)

z:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

np_out:
[1 5 8]

tf_out:
[1 5 8]
